version: "2.1"
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=trademotors
      - MYSQL_USER=trademotors
      - MYSQL_PASSWORD=sitture2
      - MYSQL_ROOT_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    environment: 
      - DJANGO_SETTINGS_MODULE=gp_cars.settings.docker
      - MYSQL_DATABASE=trademotors
      - MYSQL_USER=trademotors
      - MYSQL_PASSWORD=sitture2
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
